#!/bin/bash
dpkg-reconfigure locales tzdata keyboard-configuration
rm -rf /etc/motd
mv -f /etc/new.motd /etc/motd
apt-get update -y
apt-get upgrade -y
apt-get install --no-install-recommends ubuntu-restricted-extras wget curl git lbzip2 bzip2 unrar p7zip-full xarchiver engrampa ntfs-3g gvfs gvfs-fuse gvfs-backends samba smbclient cifs-utils sakura mousepad firefox chromium-browser vnstat xserver-xorg-video-fbdev xserver-xorg xinit openvpn network-manager network-manager-openvpn network-manager-openvpn-gnome network-manager-gnome lxqt lxqt-core lxqt-themes gnome-icon-theme gnome-disk-utility gnome-screenshot lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings i3-wm i3status i3blocks i3lock dmenu nitrogen feh scrot uget kodi weechat weechat-plugins pulseaudio pavucontrol vlc volumeicon-alsa screen gparted zram-config openjdk-14-jdk python2 python3 squid gimp xterm openbox pcmanfm pcmanfm-qt thunar thunar-volman libexo-1-0 ufw hdparm -y
apt-get autoremove --purge -y
apt-get autoclean -y
mkdir -p /etc/lightdm/
mkdir -p /etc/squid/
mkdir -p /home/pi/Chromium/
mkdir -p /home/
mkdir -p /home/pi/
mkdir -p /home/pi/Pictures/
mkdir -p /home/pi/Desktop/
mkdir -p /home/pi/Downloads/
cd /home/pi/
mkdir -p /home/pi/.config/i3/
mkdir -p /home/pi/.config/i3status/
mkdir -p /home/pi/.fonts/
mkdir -p /usr/share/fonts/
mkdir -p /usr/local/share/fonts/
git clone https://github.com/iSc0ttyathon/custom-rpi4-os.git
cd custom-rpi4-os
mv /home/pi/custom-rpi4-os/feather.ttf /home/pi/.fonts/
mv /home/pi/custom-rpi4-os/i3-status-config /home/pi/.config/i3status/config
mv /home/pi/custom-rpi4-os/i3-wm-config /home/pi/.config/i3/config
mv /home/pi/custom-rpi4-os/Desktop.png /home/pi/Pictures/Desktop.png
mv /home/pi/custom-rpi4-os/Chromium /home/pi/Chromium/
mv /home/pi/custom-rpi4-os/RPi.jpg /home/pi/Pictures/RPi.jpg
chmod -R 0777 /home/pi/Chromium/
chmod -R 0777 /home/pi/Chromium/Chromium
chmod -R 0777 /home/
chmod -R 0777 /home/pi/
rm -rf /etc/samba/smb.conf
{ echo [global] ; echo netbios name = DesktopPi ; echo workgroup = WORKGROUP ; echo interfaces = 192.168.0.1/8 ; echo ; echo [hdd] ; echo comment = linux ; echo path = /media/ ; echo browseable = yes ; echo guest ok = yes ; echo read only = no ; echo create mask = 7777 ; echo directory mask = 7777 ; echo ; echo [root] ; echo comment = Linux ; echo path = / ; echo browseable = yes ; echo guest ok = yes ; echo read only = no ; echo create mask = 7777 ; echo directory mask = 7777 ; echo ; echo [home] ; echo comment = Linux ; echo path = /home/ ; echo browseable = yes ; echo guest ok = yes ; echo read only = no ; echo create mask = 7777 ; echo directory mask = 7777 ; } >> /etc/samba/smb.conf
passwd pi
passwd root
smbpasswd -a pi
smbpasswd -a root
systemctl disable --now squid
systemctl disable --now nmbd
systemctl enable lightdm
systemctl enable NetworkManager
systemctl enable vnstat
systemctl enable smbd
rm -rf /etc/lightdm/lightdm-gtk-greeter.conf
cd /home/pi/custom-rpi4-os/
mv /home/pi/custom-rpi4-os/lightdm-gtk-greeter.conf /etc/lightdm/
cd /home/pi/custom-rpi4-os/
rm -rf /etc/squid/squid.conf
mv /home/pi/custom-rpi4-os/squid.conf /etc/squid/
snap install chromium
apt-get autoremove --purge -y
apt-get autoclean -y
ufw disable
echo Your system needs a final reboot!
sleep 5s
echo Rebooting right now!
sleep 1s
shutdown -r now
